Repository voxel51/platform-integrations, pull requests merged in 2020-01, with the labels that each got.

#9 More consistency and improvements
  README.md
  egress/.gitignore
  egress/README.md
  egress/env.json-example
  egress/event.json
  egress/samconfig.toml
  egress/src/app.py
  egress/src/requirements.txt
  egress/template.yaml
  ingress/README.md
  ingress/src/app.py
  ingress/template.yaml
Labels: documentation, enhancement

#11 Fix slack path issue
  slack/README.md
  slack/index.js
  slack/package.json
Labels: bug, documentation

#12 Expire time config
  egress/template.yaml
  ingress/README.md
  ingress/src/app.py
  ingress/template.yaml
Labels: enhancement
